version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-web-browsers
    platform: linux/amd64
    volumes:
      - .:/home/app
    ports:
      - "3030:3030"
    environment:
      - LANG=en_US.UTF-8
    command: >
      sh -c "service dbus start && service redis-server start && su - app -c 'npm install && pm2-runtime start ecosystem.config.js'"
    profiles:
      - debian

  node16-chromium:
    build:
      context: .
      dockerfile: ./docker/node16-chromium/Dockerfile
    container_name: node16-chromium
    platform: linux/arm64
    volumes:
      - .:/home/app
    ports:
      - "3030:3030"
    environment:
      - LANG=en_US.UTF-8
    command: >
      sh -c "service dbus start && service redis-server start && su - app -c 'npm install && pm2-runtime start ecosystem.config.js'"
    profiles:
      - default
      - macos